export { default as App } from './App'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Profile } from './Profile'
export { default as Posts } from './Posts'
export { default as FeaturedPosts } from './FeaturedPosts'
